stages:
  - build_container

.build:
  stage: build_container
  script:
    - echo "here"

release_build:
  extends: .build
  script:
    - echo $CI_COMMIT_TAG 
  rules:
    - if: $CI_COMMIT_BRANCH == "master"