stages:
  - build_container

.build:
  stage: build_container
  script:
    - echo "here1"

release_build:
  extends: .build
  script:
    - echo $CI_PIPELINE_SOURCE
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "merge_request_event"