stages:
  - build_container

.build:
  stage: build_container
  script:
    - echo "here2112"
    

release_build:
  extends: .build
  script:
    - echo ${DOCKER_SECRET}
  rules:
    - if: $CI_COMMIT_BRANCH == "master"