stages:
  - build_container

.build:
  stage: build_container
  script:
    - echo "here"

release_build:
  extends: .build
  script:
    - echo $CI_PIPELINE_SOURCE
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
