variables:
  SA_PASSWORD_YAML_FILE: $DOCKER_SECRET
stages:
  - build_container

.build:
  stage: build_container
  script:
    - echo "here2112"
    

release_build:
  extends: .build
  script:
    - echo "123 ${SA_PASSWORD_YAML_FILE}"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"